import { PocketGuideMovieDetail } from "../types/PocketGuideMovieDetail";

export const pocketGuideMovieList: PocketGuideMovieDetail[] = [
  {
    title: "Sonic 3: O Filme",
    session: "Sessão 2D",
    rate: "12 Anos",
    screen: "Sala 4",
    time: ["16:20"],
    language: "Legendado",
  },
  {
    title: "Kayara - A princesa inca",
    session: "Sessão 2D",
    rate: "Livre",
    screen: "Sala 4",
    time: ["15:00", "16:50"],
    language: "Dublado",
  },
  {
    title: "Ainda Estou Aqui",
    session: "Sessão 2D",
    rate: "14 Anos",
    screen: "Sala 1",
    time: ["20:30"],
    language: "Dublado",
  },
  {
    title: "Bridget Jones: Louca Pelo Garoto",
    session: "Sessão 2D",
    rate: "14 Anos",
    screen: "Sala 2",
    time: ["16:00", "18:20", "20:45"],
    language: "Legendado",
  },
  {
    title: "Capitão América: Admirável Mundo Novo",
    session: "Sessão 3D",
    rate: "14 Anos",
    screen: "Sala 3",
    time: ["14:00"],
    language: "Dublado",
  },
  {
    title: "Capitão América: Admirável Mundo Novo",
    session: "Sessão 2D",
    rate: "14 Anos",
    screen: "Sala 2",
    time: ["15:20", "17:40", "20:00"],
    language: "Dublado",
  },
  {
    title: "Capitão América: Admirável Mundo Novo",
    session: "Sessão 2D",
    rate: "14 Anos",
    screen: "Sala 1",
    time: ["16:20", "18:40", "21:00"],
    language: "Dublado",
  },
  {
    title: "Mufasa: O Rei Leão",
    session: "Sessão 2D",
    rate: "10 Anos",
    screen: "Sala 2",
    time: ["16:10"],
    language: "Dublado",
  },
  {
    title: "Mufasa: O Rei Leão",
    session: "Sessão 2D",
    rate: "10 Anos",
    screen: "Sala 4",
    time: ["18:00"],
    language: "Legendado",
  },
  {
    title: "O Auto da Compadecida 2",
    session: "Sessão 2D",
    rate: "12 Anos",
    screen: "Sala 5",
    time: ["20:20"],
    language: "Nacional",
  },
];
