export type Schedule = {
  idSistema: string;
  dataInicio: string;
  dataFim: string;
  complexo: string;
  idUnidade: string;
  sala: string;
  versao: string;
  idioma: string;
  horario0: string;
  horario1: string;
  horario2: string;
  horario3: string;
  horario4: string;
  horario5: string;
  horario6: string;
  horario7: string;
  idHtticket: string;
  idERP: string;
  idFilme: string;
  filmeUrl: string;
};
